# Generated by Django 3.1.7 on 2021-03-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('imagen_1', models.ImageField(blank=True, help_text='360x360', null=True, upload_to='proyectos')),
                ('imagen_2', models.ImageField(blank=True, help_text='360x360', null=True, upload_to='proyectos')),
                ('imagen_3', models.ImageField(blank=True, help_text='360x360', null=True, upload_to='proyectos')),
                ('imagen_4', models.ImageField(blank=True, help_text='360x360', null=True, upload_to='proyectos')),
                ('cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_proyecto', models.CharField(blank=True, max_length=50, null=True)),
                ('lugar', models.CharField(blank=True, max_length=50, null=True)),
                ('anio', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Proyectos',
            },
        ),
    ]
