# Generated by Django 3.1.7 on 2021-03-14 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0002_auto_20210313_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectos',
            name='tipo_proyecto',
        ),
    ]
