# Generated by Django 3.1.7 on 2021-03-14 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0003_remove_proyectos_tipo_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='tipo_proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proyectos.tipo_proyectos'),
        ),
    ]
