# Generated by Django 3.1.7 on 2021-03-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0002_auto_20210310_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construlaba',
            name='logo',
        ),
        migrations.AddField(
            model_name='construlaba',
            name='horario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='construlaba',
            name='logo_1',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='favicon'),
        ),
        migrations.AddField(
            model_name='construlaba',
            name='logo_2',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='favicon'),
        ),
        migrations.AddField(
            model_name='construlaba',
            name='mision',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='construlaba',
            name='vision',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
