# Generated by Django 3.1.7 on 2021-03-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0003_auto_20210313_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('oficina', models.CharField(blank=True, max_length=100, null=True)),
                ('planta', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '4. Dirección',
            },
        ),
        migrations.AlterModelOptions(
            name='construlaba',
            options={'verbose_name_plural': '1. Construlaba'},
        ),
        migrations.AlterModelOptions(
            name='contacto_redes',
            options={'verbose_name_plural': '3. Contácto Redes Sociales'},
        ),
        migrations.AlterField(
            model_name='construlaba',
            name='favicon_1',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='favicon'),
        ),
        migrations.AlterField(
            model_name='construlaba',
            name='favicon_2',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='favicon'),
        ),
        migrations.AlterField(
            model_name='construlaba',
            name='logo_horizontal_2',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='favicon'),
        ),
    ]
