# Generated by Django 3.1.7 on 2021-03-14 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0005_auto_20210313_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencia',
            options={'verbose_name_plural': '5. Experiencia'},
        ),
    ]
