# Generated by Django 3.1.7 on 2021-03-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0006_auto_20210313_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria_construlaba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='construlaba')),
            ],
            options={
                'verbose_name_plural': '2. Galeria_construlaba',
            },
        ),
    ]
