# Generated by Django 3.1.7 on 2021-03-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0007_galeria_construlaba'),
    ]

    operations = [
        migrations.AddField(
            model_name='construlaba',
            name='representante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
