# Generated by Django 3.1.7 on 2021-03-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0008_construlaba_representante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo_trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, help_text='imagenes 90*90', null=True, upload_to='equipo')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('detalle', models.TextField(blank=True, max_length=500, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'verbose_name_plural': '6. Equipo de trabajo',
            },
        ),
    ]
